# Generated by Django 5.1.1 on 2025-09-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="carrier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("att", "AT&T"),
                    ("verizon", "Verizon"),
                    ("tmobile", "T-Mobile"),
                    ("sprint", "Sprint"),
                    ("uscellular", "US Cellular"),
                    ("googlefi", "Google Fi"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="sosalert",
            name="delivered_to",
            field=models.TextField(),
        ),
    ]
